version: '2'
services:
    rest-app:
        image: rest
        external_links:
            - rest-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/rest
        ports:
            - 8080:8080
    rest-postgresql:
        extends:
            file: postgresql.yml
            service: rest-postgresql
